/** Cache data generated by the plugin. */
declare module '.cache/storybook-addon-metadata' {
  import type { ParsedStoryFile, SerializedFileNode, Uids } from '@/types';

  interface Caches {
    [projectId: string]: {
      /** The base path that relative paths use. */
      basePath: string;
      /** The serialized tree. */
      tree: SerializedFileNode;
      /** The uids that were generated. */
      uids: Uids;
      /** Stories that were found, but not used during tree generation. */
      unusedStories: ParsedStoryFile[];
    };
  }
  const exported: Caches;

  export default exported;
}

/** Individual storybook instance cache results. */
declare module '.cache/storybook-addon-metadata/*' {
  /** The base path that relative paths use. */
  const basePath: string;
  /** The serialized tree. */
  const tree: SerializedFileNode;
  /** The uids that were generated. */
  const uids: Uids;
  /** Stories that were found, but not used during tree generation. */
  const unusedStories: ParsedStoryFile[];
}
