name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      - next

jobs:
  test-deploy:
    name: Test Deployments
    runs-on: ubuntu-latest
    if:
      "${{ !contains(github.event.pull_request.labels.*.name, 'skip-ci') }} && ${{
      !contains(github.event.head_commit.message, 'skip ci')}}"
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          cache: npm
          node-version-file: .nvmrc

      - name: Install Dependencies
        run: npm ci

      - name: Typecheck
        run: npm run tsc

      - name: Run Tests
        run: npm run test

      # - name: Upload results to Codecov
      #   uses: codecov/codecov-action@v5
      #   with:
      #     token: ${{ secrets.CODECOV_TOKEN }}

      - name: Build Addon
        run: npm run build

      # - name: Set Outputs
      #   run:
      #     echo "${{contains(github.event.pull_request.labels.*.name, 'skip-release')}} ||
      #     ${{contains(github.event.head_commit.message, 'skip release')}}" >> "$GITHUB_OUTPUT"
      #   env:
      #     GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
